name: word-families
on: [push]
jobs:
  run-karma-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install node deps
        run: npm ci
      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test
  run-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
      - name: Install node deps
        run: npm ci
      - name: Cache local playwright cache
        uses: actions/cache@v3
        with:
          path: /root/.cache/ms-playwright/
          key: ${{ runner.os }}-playwright
      - name: Install playwright managed browsers
        run: npx playwright install chromium
      - name: Install playwright system deps
        run: sudo apt-get install libgbm1
      - name: Start shadow-cljs server
        run: npx shadow-cljs start
      - name: Compile application
        run: npm run release
      - name: Compile E2E tests
        run: npx shadow-cljs compile e2e-test
      - name: Run E2E tests
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run e2e
